version: '3.8'
services:
  django:
    container_name: django_c
    build:
      context: ./django
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    volumes:
      - ./django:/app_django
      - ./django/static:/app_django/staticfiles
      - ./media:/app_django/media
    networks:
      - transcendance

  postgres:
    image: postgres:latest
    container_name: postgres_c
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendance

  redis:
    image: redis:latest
    container_name: redis_c
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - transcendance

  nginx:
    container_name: nginx_c
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./django/static:/app_django/staticfiles
      - ./media:/app_django/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    restart: on-failure
    networks:
      - transcendance


volumes:
  postgres_data:
  redis_data:

networks:
  transcendance:
    driver: bridge
